version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-api
    env_file:
      - .env
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3001:3000"
    depends_on:
      - mssql 
      - mysql
    links: 
      - mysql
      - mssql
    networks:
      devnetwork:
  mysql:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: mysql.Dockerfile
    container_name: mysql
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    volumes:
      - "./mysql_volume:/var/lib/mysql"
    networks:
      devnetwork:
  mssql:
    build:
      context: .
      dockerfile: mssql.Dockerfile
    container_name: mssql
    env_file:
      - mssql.env
    ports:
      - "1433:1433"
    volumes:
      - "./mssql_volume:/var/opt/mssql"
      - "./docker/mssql/mssql-script.sql:/usr/config/setup.sql"
    networks:
      devnetwork:
networks:
  devnetwork:
    driver: bridge

